### ISSUE TITLE
Unable to pull metrics data

### ISSUE THREAD

**Issue by maygolk** [Redislabs-Solution-Architects/ecstats#3]
$ python pullElasticCacheStats.py pullStatsConfig.json
Grab a coffee this script takes a while...
Writing Headers
Gathring data...
Getting node mkanani-001 details
Getting node mkanani-002 details
Traceback (most recent call last):
  File "pullElasticCacheStats.py", line 256, in <module>
    processAWSAccount()
  File "pullElasticCacheStats.py", line 236, in processAWSAccount
    writeCosts(outputFile)
  File "pullElasticCacheStats.py", line 215, in writeCosts
    Metrics=['UnblendedCost'])
  File "/Users/maygolkananizadeh/Documents/Solution_Architects/EC2RL/.env/lib/python2.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/maygolkananizadeh/Documents/Solution_Architects/EC2RL/.env/lib/python2.7/site-packages/botocore/client.py", line 559, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/maygolkananizadeh/Documents/Solution_Architects/EC2RL/.env/lib/python2.7/site-packages/botocore/client.py", line 607, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/maygolkananizadeh/Documents/Solution_Architects/EC2RL/.env/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Filter.And[0].Dimensions.Values[0], value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>

**Comment by tleung999** [comment]
I am getting the same error.   I got through 93 nodes before the following same error occured.

```
  File "pullElasticCacheStats.py", line 256, in <module>
    processAWSAccount()
  File "pullElasticCacheStats.py", line 236, in processAWSAccount
    writeCosts(outputFile)
  File "pullElasticCacheStats.py", line 215, in writeCosts
    Metrics=['UnblendedCost'])
  File "/Users/tonyl/peek/redis/EC2RL/.env/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/tonyl/peek/redis/EC2RL/.env/lib/python2.7/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/tonyl/peek/redis/EC2RL/.env/lib/python2.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/tonyl/peek/redis/EC2RL/.env/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Filter.And[0].Dimensions.Values[0], value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
```

**Comment by maguec** [comment]
@tleung999  The quick work around is to add region to your configuration file:

```
{
    "outputFile": "stats",
    "region": "us-west-1"
}
```
We'll have a better fix later

**Comment by maguec** [comment]
@tleung999 We've reworked the configuration so this is no longer an issue.  Please pull and reconfigure
